function T = ctXsfFatigueSamplingTable(fatigue)
%CTXSFFATIGUESAMPLINGTABLE  Sampling-adequacy table of the fatigue module.

s = fatigue.sampling;

T = table(s.dt_save, s.fs, s.f_vortex_max, s.f_peak_data, s.f_significant_max_data, ...
          s.f_required, s.samples_per_shortest_period, s.min_samples_per_period, ...
          s.warning_samples_per_period, s.is_adequate_20, s.is_adequate_10, ...
          string(s.status), s.reference_section_z_over_D_paper, ...
    'VariableNames', ...
    {'dt_save_s', 'sampling_frequency_Hz', 'f_vortex_max_Hz', ...
     'f_peak_data_Hz', 'f_significant_max_data_Hz', 'f_required_Hz', ...
     'samples_per_shortest_period', 'recommended_min_samples_per_period', ...
     'warning_min_samples_per_period', 'is_adequate_for_20_samples_rule', ...
     'is_above_10_samples_warning_rule', 'sampling_status', ...
     'reference_section_z_over_D_paper'});
end
